### ISSUE TITLE
Enable to comment

### ISSUE THREAD

**Issue by SukJinKim** [zoomKoding/zoomkoding.com#2]
형님! 방금 아래 주소에 댓글 작성했는데 'Error: utterances is not installed on zoomkoding/zoomkoding.com. If you own this repo, install the app. Read more about this change in the PR.'라는 에러가 뜨면서 댓글이 안 달려요!

[https://www.zoomkoding.com/gatsby-starter-zoomkoding-introduction/](url)

**Comment by zoomKoding** [comment]
레포에 권한 부여를 깜빡했네요~ 석진님 감사해요^^
