### ISSUE TITLE
[Issue] projects image link & netlify domain

### ISSUE THREAD

**Issue by C-Designer** [zoomKoding/zoomkoding.com#4]
안녕하세요 :) 답변 감사드립니다!

1. projects의 이미지는 상대경로를 통해 등록이 안됩니다 ㅠㅠ
2. 도메인을 사서 netlify를 통해 배포하는 형태인가요?? 깃허브 페이지로 배포할 방법은 없을까요?
3. about.js의 구조를 따라야한다며 links의 [post, github, demo, googlePlay, appStore]가 모두 포함되어있어야 한다고 반환됩니다 / links를 통째로 빼버려도 에러가 뜨네요
<img width="523" alt="스크린샷 2021-07-05 오전 1 09 11" src="https://user-images.githubusercontent.com/69777689/124391871-9cde1900-dd2d-11eb-98fc-602c0d44ec40.png">

```
links: {
          post:'',
          googlePlay:'',
          appStore:'',
          demo:'',
          github:''
        }
```
이렇게 하니 실행은 됩니다

4. github codeblock style을 좋아하는데 제가 개인적으로 변경이 가능한가요?

**Comment by zoomKoding** [comment]
C-Designer님 안녕하세요! 
남겨주신 부분들이 다 한번씩 봐볼만한 것들이라 이슈를 분리해서 대응해보도록 하겠습니다!
이슈 남겨주셔서 감사합니다 C-Designer님👍😊
