### ISSUE TITLE
[Feedback] darkmode, nav bar, toc

### ISSUE THREAD

**Issue by C-Designer** [zoomKoding/zoomkoding.com#5]
안녕하세요! 테마 잘쓰겠습니다 ㅎㅎ

개인적인 바램으로 남깁니다! 참고해주시면 감사하겠습니다:)
1. 다크모드 지원 (상단탭 우측란에 있었으면 좋겠습니다!)
2. 스크롤 올릴때 상단바가 내려오게끔 (모바일에서 편리하더라구요!)
3. 목차사항이 velog처럼 부드러웠으면 좋겠습니다

**Comment by zoomKoding** [comment]
다 너무 좋은 제안들이네요!
따로 이슈로 빼서 하나씩 순차적으로 반영해보도록 하겠습니다!👍
